<?php
/**
 * Arrays used to generate dummy content.
 *
 * @package SLJ Dummy Content
 * @subpackage Input
 */

$html_elements = array( 'h1', 'h2', 'h3', 'h4', 'h5', 'blockquote' );

$inline_elements = array( 'strong', 'em', 'strike', 'small' );

$headers = array(
	"I'm serious as a heart attack",
	"I can do that",
	"Is she dead, yes or no?",
	"Hold on to your butts",
	"No, motherfucker",
	"Are you ready for the truth?",
	"We happy?",
	"I gotta piss",
	"No man, I don't eat pork",
	"Uuummmm, this is a tasty burger!",
	"If you have an opportunity to use your voice you should use it.",
	"I get paid all day, every day, which is almost too much for a sensitive artist.",
	"What kills me is that everybody thinks I like jazz.",
	"Want to know what the 'L.' in Samuel L. Jackson means? None of your fucking business.",
	"Enough is enough! I have had it with these motherfucking snakes on this motherfucking plane!",
	"Everybody listen! We have to put a barrier between us and the snakes!",
	"All praises to the PlayStation.",
	"Well, that's good news. Snakes on crack.",
	"Do as I say and you live.",
	"Turn this big motherfucker left, Troy!",
	"Eddie Kim somehow managed to fill the plane with poisonous snakes.",
	"Sit your ass down, Clarence.",
	"I'm about to open some fucking windows!",
	"You shooting the ball, what's your name?",
	"I guess I should speak louder so you can hear me?",
	"You still want to work S.W.A.T?",
	"They only roll in John Woo movies, not in real life.",
	"The reason we're gathered here on our God-given, much-needed day of rest is that we have a Polish hostage.",
	"Let's try to get in the killing mode.",
	"Yeah. What the hell. Mount up.",
	"Flip a bitch!",
	"I need your A-game boys... and girl.",
	"Drop Fruit of the Loomski in the A-car.",
	"How can I trust a man who won't eat a good old-fashioned American hotdog?",
	"There's coyotes up here.",
	"Hey! Get the hell off my damn property.",
	"Street. Don't beat him so badly I can't get a rematch, all right?",
	"Hold the phone. Six, seven, eight, nine, ten of Spades. Deke!",
	"Ten of Spades. Spade flush.",
	"But I found you. So many sacrifices just to find you.",
	"Are you ready for the truth?",
	"This is an art gallery, my friend, and this is a piece of art.",
	"I think this is where we shake hands.",
	"Is she dead, yes or no?",
	"To her dumb country ass, Compton is Hollywood.",
	"How old is that machine gun shit?",
	"I didn't hear you wash your hands.",
	"I'm serious as a heart attack.",
	"My ass may be dumb, but I ain't no dumbass.",
	"Oh, ya'll a couple Cheech and Chongs, huh?",
	"Girl, don't make me put my foot in your ass.",
	"Try not to tear his clothes off, OK? They're new.",
	"Last chance, motherfucker. You sure?",
	"Look at you and your free ass. Come here, boy, gimme a motherfuckin' hug.",
	"You keep fuckin' with me, you're gonna be asleep forever.",
	"You can't trust Melanie but you can trust Melanie to be Melanie.",
	"Come on man! If it wasn't for me, you wouldn't HAVE that motherfuckin' boat!",
	"Oh shit, that shit rhymes! 'Blew Beau-mont's, brains out!'",
	"Let me have a screwdriver homes.",
	"It would be totally painless - they'd just slip into unconsciousness and die.",
	"What a complete slob!",
	"Access main program. Access main security. Access main program grid.",
	"God damn it! I hate this hacker crap!",
	"You got to cool that shit off. And that's the double-truth, Ruth.",
	"The boy has exceptional skills.",
	"Protect the senator at all costs.",
	"This party's over.",
	"We're keepers of the peace, not soldiers.",
	"I think it is time we inform the senate that our ability to use the force has diminished.",
	"We will not be hostages to be bartered, Dooku.",
	"It's Giuliani time!",
	"It's my duty to please that booty!",
	"You wouldn't know Egyptian cotton if the Pharaoh himself sent it to you, you knockoff-wearing motherfucker!",
	"Who got you that Jets tryout?",
	"Do you think that makes me less dangerous, or more dangerous?",
	"I'm gonna fuck you up for making me run!",
	"What's up with the 'cornbread' talk, man?",
	"I know cats who'd take out whole zipcodes for that kind of cheese.",
	"Yes, they deserved to die and I hope they burn in hell!",
	"Where - is - my - super - suit?",
	"You tell me where my suit is, woman!",
	"The guy has me on a platter and he won't shut up!",
	"I don't see anyone from the old days, Bob.",
	"To tell you the truth, I'd rather go bowling.",
	"Waste the motherfuckers.",
	"I was not going to stand by and see another Marine die just to live by those fucking rules.",
);

$strings = array(
	"Normally, both your asses would be dead as fucking fried chicken, but you happen to pull this shit while I'm in a transitional period so I don't wanna kill you, I wanna help you. But I can't give you this case, it don't belong to me. Besides, I've already been through too much shit this morning over this case to hand it over to your dumb ass.",
	"Well, the way they make shows is, they make one show. That show's called a pilot. Then they show that show to the people who make shows, and on the strength of that one show they decide if they're going to make more shows. Some pilots get picked and become television programs. Some don't, become nothing. She starred in one of the ones that became nothing.",
	"The path of the righteous man is beset on all sides by the iniquities of the selfish and the tyranny of evil men. Blessed is he who, in the name of charity and good will, shepherds the weak through the valley of darkness, for he is truly his brother's keeper and the finder of lost children. And I will strike down upon thee with great vengeance and furious anger those who would attempt to poison and destroy My brothers. And you will know My name is the Lord when I lay My vengeance upon thee.",
	"Do you see any Teletubbies in here? Do you see a slender plastic tag clipped to my shirt with my name printed on it? Do you see a little Asian child with a blank expression on his face sitting outside on a mechanical helicopter that shakes when you put quarters in it? No? Well, that's what you see at a toy store. And you must think you're in a toy store, because you're here shopping for an infant named Jeb.",
	"Your bones don't break, mine do. That's clear. Your cells react to bacteria and viruses differently than mine. You don't get sick, I do. That's also clear. But for some reason, you and I react the exact same way to water. We swallow it too fast, we choke. We get some in our lungs, we drown. However unreal it may seem, we are connected, you and I. We're on the same curve, just on opposite ends.",
	"Now that we know who you are, I know who I am. I'm not a mistake! It all makes sense! In a comic, you know how you can tell who the arch-villain's going to be? He's the exact opposite of the hero. And most times they're friends, like you and me! I should've known way back when... You know why, David? Because of the kids. They called me Mr Glass.",
	"You think water moves fast? You should see ice. It moves like it has a mind. Like it knows it killed the world once and got a taste for murder. After the avalanche, it took us a week to climb out. Now, I don't know exactly when we turned on each other, but I know that seven of us survived the slide... and only five made it out. Now we took an oath, that I'm breaking now. We said we'd say it was the snow that killed the other two, but it wasn't. Nature is lethal but it doesn't hold a candle to man.",
	"Look, just because I don't be givin' no man a foot massage don't make it right for Marsellus to throw Antwone into a glass motherfuckin' house, fuckin' up the way the nigger talks. Motherfucker do that shit to me, he better paralyze my ass, 'cause I'll kill the motherfucker, know what I'm sayin'?",
	"Now that there is the Tec-9, a crappy spray gun from South Miami. This gun is advertised as the most popular gun in American crime. Do you believe that shit? It actually says that in the little book that comes with it: the most popular gun in American crime. Like they're actually proud of that shit.",
	"My money's in that office, right? If she start giving me some bullshit about it ain't there, and we got to go someplace else and get it, I'm gonna shoot you in the head then and there. Then I'm gonna shoot that bitch in the kneecaps, find out where my goddamn money is. She gonna tell me too. Hey, look at me when I'm talking to you, motherfucker. You listen: we go in there, and that nigga Winston or anybody else is in there, you the first motherfucker to get shot. You understand?",
	"You really need to consider the message you're sending this boys by ending the lockout. It's the same message that we as a culture send to our professional athletes; and that is that they are above the law. If these boys cannot honor the simple rules of a basketball contract, how long do you think it will be before they're out there breaking the law? I played ball here at Richmond High 30 years ago. It was the same thing then; some of my teammates went to prison, some of them even ended up dead. If you vote to end the lockout, you won't have to terminate me; I'll quit.",
	"N****r is a degrogatory term used to insult our ancestors. See, if a white man used it, you'd be ready to fight. Your using it teaches him to use it. You're saying it's cool. Well, it's not cool, and when you're around me, I don't want to hear that shit! Are we clear?",
	"Look. Just give me the team I asked for. You can even call it your *shit list* team. So that way, if anything goes wrong, you can put all the blame on me. It'll be just like old times.",
	"Now that we know who you are... I know who I am. I'm not a mistake! It all makes sense. In a comic, you know how you can tell who the arch-villain's going to be? He's the exact opposite of the hero, and most time's they're friends, like you and me. I should've known way back when. You know why, David? Because of the kids. They called me Mr. Glass.",
	"You could have been a tax accountant. You could have owned your own gym. You could have opened a chain of restaurants. You could've done of ten thousand things, but in the end, you chose to protect people. *You* made that decision, and I find that very, very interesting.",
	"Do you see any Teletubbies in here? Do you see a slender plastic tag clipped to my shirt with my name printed on it? Do you see a little Asian child with a blank expression on his face sitting outside on a mechanical helicopter that shakes when you put quarters in it? No? Well, that's what you see at a toy store. And you must think you're in a toy store, because you're here shopping for an infant named Jeb.",
	"Do you know what the scariest thing is? To not know your place in this world, to not know why you're here.",
	"Your bones don't break, mine do. That's clear. Your cells react to bacteria and viruses differently than mine. You don't get sick, I do. That's also clear. But for some reason, you and I react the exact same way to water. We swallow it too fast, we choke. We get some in our lungs, we drown. However unreal it may seem, we are connected, you and I. We're on the same curve, just on opposite ends.",
	"He put himself in a position where he was going to have to do ten years in prison, that's what he did. And if you know Beaumont, you know ain't no god damn way he can do ten years. And if you know that, then you know Beaumont's gonna do anything Beaumont can to keep from doing them ten years, including telling the federal government any and every motherfucking thing about my black ass. Now that my friend is a clear cut case of him or me. And you best believe it ain't gonna be me.",
	"The lysine contingency is intended to prevent the spread of the animals in case they ever get off the island. Dr. Wu inserted a gene that makes a single faulty enzyme in protein metabolism. The animals can't manufacture the amino acid lysine. Unless they're continually supplied with lysine by us, they'll slip into a coma and die.",
	"Now, look at this next entry, here's the kicker - White Rabbit Object. Whatever it is, it did it all. But with the key-checks off, the computer didn't file the keystrokes, so the only way to find them now is to go through the computer's lines of code one by one.",
	"My people, my people, what can I say; say what I can. I saw it but didn't believe it; I didn't believe what I saw. Are we gonna live together? Together are we gonna live?",
	"Yes, children, this is the cool-out corner. We're slowing it down for all the lovers in the house. I'll be giving you all the help you need. Musically, that is.",
	"WE LOVE ROLL CALL, Y'ALL! Boogie Down Productions, Rob Base, Dana Dane, Marley Marl, Olatunji, Chuck D, Ray Charles, EPMD, EU, Alberta Hunter, Run-D.M.C., Stetsasonic, Sugar Bear, John Coltrane, Big Daddy Kane, Salt-n-Pepa, Luther Vandross, McCoy Tyner, Biz Markie, New Edition, Otis Redding, Anita Baker, Thelonious Monk, Marcus Miller, Branford Marsalis, James Brown, Wayne Shorter, Tracy Chapman, Miles Davis, Force MDs, Oliver Nelson, Fred Wesley, Maceo, Janet Jackson, Louis Armstrong, Duke Ellington, Jimmy Jam, Terry Lewis, George Clinton, Count Basie, Mtume, Stevie Wonder, Bobby McFerrin, Dexter Gordon, Sam Cooke, Parliament-Funkadelic, Al Jarreau, Teddy Pendergrass, Joe Williams, Wynton Marsalis, Phyllis Hyman, Sade, Sarah Vaughn, Roland Kirk, Keith Sweat, Kool Moe Dee, Prince, Ella Fitzgerald, Dianne Reeves, Aretha Franklin, Bob Marley, Bessie Smith, Whitney Houston, Dionne Warwick, Steel Pulse, Little Richard, Mahalia Jackson, Jackie Wilson, Cannonball AND Nat Adderley, Quincy Jones Marvin Gaye, Charles Mingus AND Marion Williams. We wanna thank you all for makin' our lives just a little brighter here on We Love Radio!",
	"Today's temperature's gonna rise up over 100 degrees, so there's a Jheri curl alert! That's right, Jheri curl alert. If you have a Jheri curl, stay in the house or you'll end up with a permanent black helmet on your head fuh-eva!",
	"America is a war and you are on the other side. How's a black man ever going to get a fair trial with the enemy on the bench and in the jury box?. My life in white hands? You Jake, that's how. You are my secret weapon because you are one of the bad guys. You don't mean to be but you are. It's how you was raised. Nigger, negro, black, African-american, no matter how you see me, you see me different, you see me like that jury sees me, you are them. Now throw out your points of law Jake. If you was on that jury, what would it take to convince you to set me free? That's how you save my ass. That's how you save us both.",
	"We ain't no friends, Jake. We are on different sides of the line, I ain't never seen you in my part of town. I bet you don't even know where I live. Our daughters, Jake; they ain't never gonna play together.",
	"Well, you are white and I'm black. See Jake, you think just like them, that's why I picked you; you are one of them , don't you see?. Oh, you think you ain't because you eat in Claude's and you are out there trying to get me off on TV talking about black and white, but the fact is you are just like all the rest of them. When you look at me, you don't see a man, you see a black man.",
	"Yes they had weapons! You think there's a script for fighting a war without pissing somebody off? Follow the rules and nobody gets hurt? Yes, innocent people probably died. Innocent people always die but I did not exceed my orders.",
	);

$videos = array(
	'width="420" src="//www.youtube.com/embed/uMl9oYSVGlo"',
	'width="560" src="//www.youtube.com/embed/ecHDwBufZKQ"',
	'width="560" src="//www.youtube.com/embed/FLe54UPOeXw"',
	'width="560" src="//www.youtube.com/embed/crR6pBGMZ90"',
	'width="560" src="//www.youtube.com/embed/yM0wP07wD2g"',
	'width="420" src="//www.youtube.com/embed/ENjKi7NkTNE"',
	'width="560" src="//www.youtube.com/embed/zMhEOKU_hIo"',
	'width="420" src="//www.youtube.com/embed/Z2NaN_QNFUo"',
	'width="420" src="//www.youtube.com/embed/iZn1jS3rCk8"',
	);